### ISSUE TITLE
Apply Ormgap plugin to Library project

### ISSUE THREAD

**Issue by dvdrlee** [stephanenicolas/ormlite-android-gradle-plugin#1]
I have a library project which depends on OrmLite and contains all of my DAOs and database management code. My application project depends on this library project.

Here is a snippet of my build.gradle file for the the library project using 'com.android.library'

```
buildscript{
    repositories{
        mavenCentral()
    }
    dependencies{
        classpath 'com.github.stephanenicolas.ormgap:ormgap-plugin:1.0.10'
    }
}
apply plugin: 'com.android.library'
apply plugin: 'ormgap'

```

Here is the error I get when building my application:

> A problem occurred configuring project ':myLibraryProject'.
> Cannot cast object 'com.android.build.gradle.internal.api.LibraryVariantImpl_Decorated@773bc91e' with class 'com.android.build.gradle.internal.api.LibraryVariantImpl_Decorated' to class 'com.android.build.gradle.api.ApplicationVariant'

Is this a known limitation of this plugin? Is there any way I can make this build work for my project setup?

**Comment by stephanenicolas** [comment]
@dvdrlee it looks like we have a strong cast on https://github.com/stephanenicolas/ormlite-android-gradle-plugin/blob/master/ormgap-plugin/src/main/groovy/com/github/stephanenicolas/ormgap/ORMGAPPlugin.groovy line 56.

Do you wanna try to PR the lib and check if it works for you ?
(you could use instance of and make it work for both apps and libs)

I checked and that should be pretty easy to do : if X instanceof appVariant, cast it and use mergedFlavorName, otherwise if it s a lib variant, cast it and use the same property.

That should do the job. I would be happy to merge a PR in this direction quickly.

**Comment by dvdrlee** [comment]
Thanks for the suggestion. I can give it a try later this week
