### ISSUE TITLE
Improvement: Add a comment section with date time of last file generation

### ISSUE THREAD

**Issue by sim1camporeale** [stephanenicolas/ormlite-android-gradle-plugin#13]
Dear @stephanenicolas,
I want to thank you for the library you have shared with the open-source community. Yesterday I waste 8hrs of work because I update my models and missed to lunch OrmLiteConfigUtil. 
Today I started using **ormlite-gap 2.0** and I'm able to generate **ormlite_configfile** with a custom name in asset folder.
When I generated **ormlite_configfile** with `OrmLiteConfigUtil.writeConfigFile`
there was a heading section in the generated file reporting the generation date time
```
#
# generated on 2017/07/30 12:51:35
#
```
I think that will be very useful if this information will be added in generated_file from **ormlite-gap 2.0**.

Thanks for you work.
Simone

**Comment by stephanenicolas** [comment]
This had been removed from our own copy of  the util because until version
2.0 of the plugin we stored the file in the source tree of our apps. But
now that it is in the asset folder, we can add this back.

We would gratefully accept a PR on this @simone ;) Do you wanna try it ?

2017-07-31 2:57 GMT-07:00 Simone Camporeale <notifications@github.com>:

**Comment by stephanenicolas** [comment]
Re-thinking about it, I think it's not a good idea. It will break the assets merge tasks as well as it used to merge the resource merging task. We should not do this to get cacheable tasks (and incremental tasks neither). I close the issue, feel free to re-open if you find a way to preserve cacheability and add the header line.
